#!/bin/bash -e

(( UID )) && exec sudo "$0" "$@"

config_file=/.ansibleconfig

if ! [[ -e $config_file ]]; then
    read -r -p 'Config: ' AS_CONFIG
    echo "$AS_CONFIG" > "$config_file"
fi

AS_CONFIG=$(cat "$config_file")
export AS_CONFIG

exec ansible-playbook -i localhost, setup.yml
