---
- hosts: localhost
  connection: local

  vars_files:
    - vars/common.yml
    - "vars/{{ lookup('env', 'AS_CONFIG') }}.yml"

  tasks:
    - name: Get size of long to determine architecture
      command: getconf LONG_BIT
      register: long_bit
      changed_when: false

    # Used, hackily, to not reinstall AUR packages
    - name: Get list of installed packages
      command: pacman -Qq
      register: installed_packages
      changed_when: false

    - include: tasks/network.yml
    - include: tasks/ntp.yml
    - include: tasks/pacman.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/users.yml
    - include: tasks/aur.yml
    - include: tasks/sudo.yml
    - include: tasks/fonts.yml
    - include: tasks/xorg.yml
    - include: tasks/blacklist-pcspkr.yml
    - include: tasks/desktop.yml
    - include: tasks/sound.yml
    - include: tasks/basic-tools.yml
    - include: tasks/python.yml
    - include: tasks/docker.yml
    - include: tasks/email.yml
    - include: tasks/smartcard.yml
    - include: tasks/gpg.yml user=laurent
    - include: tasks/dotfiles.yml user=laurent
