---
- name: Create local user for makepkg
  user: name=makepkg shell=/bin/sh

- name: Copy aur script
  copy: src=files/bin/aur dest=/usr/local/bin/aur mode=755

- name: Install package-query dependency (yajl)
  pacman: name=yajl state=present

- name: Install yaourt dependency (package-query)
  command: /usr/local/bin/aur package-query
  when: "'package-query' not in installed_packages.stdout_lines"

- name: Install yaourt
  command: /usr/local/bin/aur yaourt
  when: "'yaourt' not in installed_packages.stdout_lines"
