---
- name: Install basic tools
  pacman:
    state: present
    name:
      - gvim
      - git
      - ack
      - postgresql
      - rsync
      - openvpn
      - pass
      - ranger
      - bc
      - net-tools
      - nfs-utils
      - unzip
