---
- name: Install i3 wm and tools
  pacman: name={{ item }} state=present
  with_items:
    - i3-wm
    - i3lock
    - i3status

- name: Install desktop utilities with pacman
  pacman: name={{ item }} state=present
  with_items:
    - dmenu
    - imagemagick
    - ghostscript
    - rxvt-unicode
    - alsa-utils
    - libnotify
    - dunst
    - redshift
    - chromium
    - scrot
    - xbindkeys

- name: Install desktop utilities with yaourt
  yaourt: name={{ item }}
  with_items:
    - py3status
    - slack-desktop
  become: yes
  become_user: makepkg

