---
- name: Install i3 wm and tools
  pacman: name={{ item }} state=present
  with_items:
    - i3-wm
    - i3lock
    - i3status

- name: Install desktop utilities with pacman
  pacman: name={{ item }} state=present
  with_items:
    - dmenu
    - rofi
    - imagemagick
    - ghostscript
    - rxvt-unicode
    - urxvt-perls
    - alsa-utils
    - libnotify
    - dunst
    - redshift
    - chromium
    - scrot
    - xbindkeys
    - sxiv
    - evince
    - xautolock

- name: Install slack
  yaourt: name=slack-desktop
  become: yes
  become_user: makepkg

