---
- name: Install i3 wm and tools
  pacman:
    state: present
    name:
      - i3-wm
      - i3lock
      - i3status

- name: Install desktop utilities with pacman
  pacman:
    state: present
    name:
      - dmenu
      - rofi
      - imagemagick
      - ghostscript
      - rxvt-unicode
      - urxvt-perls
      - libnotify
      - dunst
      - redshift
      - chromium
      - firefox
      - maim
      - xbindkeys
      - sxiv
      - feh
      - evince
      - xautolock
      - playerctl

- name: Install slack
  aur: name=slack-desktop
  become: yes
  become_user: makepkg
