---
- name: Import GPG key
  command: "gpg --keyserver keyserver.ubuntu.com --recv-keys {{ gpg_key }}"
  register: out
  become: true
  become_user: "{{ user }}"
  changed_when: "'imported: 1' in out.stderr"
