---
- name: Install wireless tools
  pacman:
    state: present
    name:
      - wpa_supplicant
      - wpa_actiond
      - dialog

- name: Enable automatic wireless connections
  service: name="netctl-auto@{{ wifi.interface }}" enabled={{ wifi.auto }}
