---
- name: Install wireless tools
  pacman: name={{ item }} state=present
  with_items:
    - wpa_supplicant
    - wpa_actiond
    - dialog

- name: Enable automatic wireless connections
  service: name="netctl-auto@{{ wifi.interface }}" state=started enabled=yes
  when: wifi.auto
