---
- name: Copy pacman configuration
  template: src=files/pacman.conf dest=/etc/pacman.conf

- name: Update package lists
  pacman: update_cache=yes
  changed_when: false

- name: Install pacman-contrib
  pacman: name=pacman-contrib state=present
