---
- name: Install Xorg base
  pacman:
    state: present
    name:
      - xorg-server
      - xorg-xprop
      - xorg-xmodmap
      - xorg-xrandr
      - xorg-xinit
      - xorg-xev
      - xorg-xset
      - xorg-xrdb
      - xorg-xbacklight

- name: Set up Xorg for Dell XPS
  pacman: name=xf86-video-intel state=present
  when: model == "Dell XPS"

- name: Set up Xorg for Home Tower
  pacman: name=xf86-video-amdgpu state=present
  when: model == "Home Tower"

- name: Set up Xorg keyboard settings
  copy: src=files/xorg/00-keyboard.conf dest=/etc/X11/xorg.conf.d/00-keyboard.conf

- name: Set up Xorg touchpad settings
  copy: src=files/xorg/00-touchpad.conf dest=/etc/X11/xorg.conf.d/00-touchpad.conf
  when: model == "Dell XPS"

- name: Install VirtualBox guest utilities
  pacman: name=virtualbox-guest-utils state=present
  when: model == "VirtualBox"

- name: Set up autoloading of VirtualBox modules
  copy: src=files/virtualbox/guest-modules dest=/etc/modules-load.d/virtualbox-guest.conf
  when: model == "VirtualBox"

- name: Configure vboxservice
  service: name=vboxservice state=started enabled=yes
  when: model == "VirtualBox"

- name: Depmod
  command: depmod
  changed_when: false
